version: '3.8'

volumes:
  postgresql_data:
    driver: local

services:
  postgresql:
    image: postgres:13.3
    volumes:
      - postgresql_data:/var/lib/postgres
    environment:
      POSTGRES_DB: movie_app
      POSTGES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432