spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5433/movie_app
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always